# Generated by Django 3.1.7 on 2021-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestNumber', models.IntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('requester', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('urgency', models.IntegerField(choices=[(1, '1 - Low'), (2, '2 - Moderate'), (3, '3 - High'), (4, '4 - Critical')], default=1)),
                ('justification', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
